import { redirect } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

/**
 * MAVERO Phase 7E — SuperEmbed official "Advanced way" server-side redirect bootstrap.
 *
 * This route reproduces the documented SuperEmbed `se_player.php` flow exactly:
 *   1. Receive `video_id`, `tmdb`, `season`/`s`, `episode`/`e` query params.
 *   2. Call `https://getsuperembed.link/` server-side with those params plus
 *      the documented player configuration parameters.
 *   3. `getsuperembed.link` returns a plain-text player URL
 *      (`https://streamingnow.mov/?play={encrypted_token}`).
 *   4. Respond with an HTTP 302 `Location` redirect to that player URL.
 *
 * The browser loads this route inside an iframe (the iframe src is
 * `mavero.../api/playback/superembed?video_id=...&tmdb=1`). The 302 redirect
 * makes the iframe navigate to `streamingnow.mov`, which is the official
 * SuperEmbed player frontend. This is architecturally identical to the
 * documented `se_player.php` integration — the iframe's initial origin is
 * same-origin with Mavero, and the redirect is issued server-side.
 *
 * What this route does NOT do:
 *   - It does NOT scrape `streamingnow.mov` or extract the encrypted `?play=`
 *     token. The token is generated by SuperEmbed's server and consumed only by
 *     the browser.
 *   - It does NOT proxy arbitrary third-party pages. The only upstream call is
 *     to the documented `getsuperembed.link` endpoint, and the only response is
 *     a 302 redirect — never the upstream content itself.
 *   - It does NOT bypass X-Frame-Options or CSP. `streamingnow.mov`'s headers
 *     apply to the browser's final navigation, not to this route's response.
 *   - It does NOT store, log, or expose the player URL. The redirect is issued
 *     and forgotten.
 *
 * Security:
 *   - The only accepted query params are `video_id`, `tmdb`, `season`/`s`,
 *     `episode`/`e`. All other params are ignored.
 *   - `video_id` is validated as a short alphanumeric string (TMDB numeric or
 *     IMDb `tt##########` form). No arbitrary URL injection is possible.
 *   - The upstream call has an 8-second timeout and follows no redirects
 *     (`getsuperembed.link` returns 200 with a text body, not a redirect).
 *   - If the upstream call fails, returns a 503 (no body leak).
 *   - The response is always a 302 redirect to an `https://` URL, or a
 *     controlled error. Never returns upstream content inline.
 *
 * Rate limiting:
 *   - `getsuperembed.link` does not document a separate rate limit, but
 *     SuperEmbed's overall API limit is 10 req/10 s/IP. This route is only
 *     called when the user actively selects the SuperEmbed source in the
 *     player, not on every page render.
 */

const GETSUPEREMBED_ORIGIN = 'https://getsuperembed.link';
const UPSTREAM_TIMEOUT_MS = 8_000;

// Documented player configuration parameters (from se_player.php).
// These are safe, non-secret cosmetic/behavioral settings.
const PLAYER_CONFIG = {
  player_font: 'Poppins',
  player_bg_color: '000000',
  player_font_color: 'ffffff',
  player_primary_color: '34cfeb',
  player_secondary_color: '6900e0',
  player_loader: '1',
  preferred_server: '0',
  player_sources_toggle_type: '2',
} as const;

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0;
}

function isValidVideoId(value: string): boolean {
  // TMDB numeric id (1-19 digits) or IMDb id (tt + 1-15 digits, or bare numeric).
  return /^[1-9][0-9]{0,18}$/.test(value) || /^tt[0-9]{1,15}$/i.test(value);
}

function parsePositiveInteger(value: string | null | undefined): number {
  if (value === null || value === undefined || value === '') return 0;
  const n = Number(value);
  return Number.isInteger(n) && n > 0 && n < 100000 ? n : 0;
}

function isPrivateHost(host: string): boolean {
  return (
    host === 'localhost' || host.endsWith('.localhost') || host.endsWith('.local') ||
    /^127(?:\.[0-9]{1,3}){3}$/.test(host) || /^10(?:\.[0-9]{1,3}){3}$/.test(host) ||
    /^192\.168(?:\.[0-9]{1,3}){2}$/.test(host) || /^0(?:\.[0-9]{1,3}){3}$/.test(host) ||
    /^169\.254(?:\.[0-9]{1,3}){2}$/.test(host) ||
    /^172\.(1[6-9]|2[0-9]|3[01])(?:\.[0-9]{1,3}){2}$/.test(host)
  );
}

export const GET: RequestHandler = async ({ url }) => {
  const videoId = url.searchParams.get('video_id');
  if (!isNonEmptyString(videoId) || !isValidVideoId(videoId)) {
    return new Response('Missing or invalid video_id', { status: 400 });
  }

  const tmdb = url.searchParams.get('tmdb') === '1' ? '1' : '0';
  const season = parsePositiveInteger(url.searchParams.get('season') ?? url.searchParams.get('s'));
  const episode = parsePositiveInteger(url.searchParams.get('episode') ?? url.searchParams.get('e'));

  const params = new URLSearchParams({
    video_id: videoId,
    tmdb,
    season: String(season),
    episode: String(episode),
    ...PLAYER_CONFIG,
  });
  const upstreamUrl = `${GETSUPEREMBED_ORIGIN}/?${params.toString()}`;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);
  let playerUrl: string;
  try {
    const response = await fetch(upstreamUrl, {
      method: 'GET',
      signal: controller.signal,
      headers: { accept: 'text/html, */*' },
      redirect: 'manual',
    });
    if (!response.ok) {
      return new Response('SuperEmbed bootstrap unavailable', { status: 503 });
    }
    playerUrl = (await response.text()).trim();
  } catch {
    return new Response('SuperEmbed bootstrap unavailable', { status: 503 });
  } finally {
    clearTimeout(timeout);
  }

  // Validate the returned URL: must be an https:// URL on a non-private host.
  // This prevents open-redirect abuse via a compromised upstream.
  if (!playerUrl.startsWith('https://')) {
    return new Response('SuperEmbed bootstrap unavailable', { status: 503 });
  }
  let parsed: URL;
  try {
    parsed = new URL(playerUrl);
  } catch {
    return new Response('SuperEmbed bootstrap unavailable', { status: 503 });
  }
  if (isPrivateHost(parsed.hostname.toLowerCase())) {
    return new Response('SuperEmbed bootstrap unavailable', { status: 503 });
  }

  throw redirect(302, playerUrl);
};
