/**
 * Third-Party Playback Ad Protection — provider/source-scoped configuration.
 * ==========================================================================
 *
 * IMPORTANT SCOPE: this module configures `Streaming Provider Playback Ad
 * Protection` ONLY — protection against ads/redirects generated by a
 * third-party streaming provider during playback of that provider's source.
 *
 * It is deliberately SEPARATE from any future first-party `MaveroAds`
 * system. There is no global ad-blocker switch anywhere in this module: the
 * setting is stored per streaming provider and per streaming source inside
 * their existing `capabilities` JSONB (the same architecture as
 * `sandbox_policy`), and it influences nothing outside playback URL
 * resolution for the specific provider/source being played.
 *
 * Storage shape (inside `streaming_providers.capabilities` /
 * `streaming_sources.capabilities`):
 *   "playback_ad_protection": true | false
 *   "playback_ad_protection_rules": { "blockedHosts": [...], "blockedPathPrefixes": [...] }  (optional, advanced)
 *
 * Effective resolution: source override → provider default → system default
 * (OFF). The system default is OFF so enabling protection is always an
 * explicit admin decision and existing providers' playback behavior is never
 * altered unexpectedly.
 */

export type PlaybackAdProtectionRules = {
  blockedHosts?: readonly string[];
  blockedPathPrefixes?: readonly string[];
};

export type PlaybackAdProtectionConfig = PlaybackAdProtectionRules & {
  enabled: boolean;
};

export const defaultPlaybackAdProtection: PlaybackAdProtectionConfig = { enabled: false };

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function explicitEnabled(capability: unknown): boolean | undefined {
  if (!isRecord(capability)) return undefined;
  const value = capability.playback_ad_protection;
  if (value === true) return true;
  if (value === false) return false;
  return undefined;
}

/**
 * Reads the optional advanced rules object for one capabilities record.
 * Malformed values are ignored (never partially trusted).
 */
function rulesFromCapabilities(capability: unknown): PlaybackAdProtectionRules {
  if (!isRecord(capability)) return {};
  const raw = capability.playback_ad_protection_rules;
  if (!isRecord(raw)) return {};
  const rules: { blockedHosts?: string[]; blockedPathPrefixes?: string[] } = {};
  if (Array.isArray(raw.blockedHosts)) {
    const hosts = raw.blockedHosts.filter((host): host is string => typeof host === 'string' && host.trim().length > 0).map((host) => host.trim().toLowerCase());
    if (hosts.length) rules.blockedHosts = hosts;
  }
  if (Array.isArray(raw.blockedPathPrefixes)) {
    const prefixes = raw.blockedPathPrefixes.filter((prefix): prefix is string => typeof prefix === 'string' && prefix.startsWith('/'));
    if (prefixes.length) rules.blockedPathPrefixes = prefixes;
  }
  return rules;
}

/**
 * Resolves the effective Third-Party Playback Ad Protection configuration
 * for a provider/source pair from their existing capabilities JSONB.
 *
 * Precedence: an explicit source-level boolean overrides the provider-level
 * boolean; when neither is explicit the system default (OFF) applies. Rules
 * are UNIONED (provider rules + source rules) so a source can tighten but
 * never silently discard its provider's rules.
 */
export function playbackAdProtectionFromCapabilities(providerCapabilities: unknown, sourceCapabilities?: unknown): PlaybackAdProtectionConfig {
  const sourceEnabled = explicitEnabled(sourceCapabilities);
  const providerEnabled = explicitEnabled(providerCapabilities);
  const enabled = sourceEnabled ?? providerEnabled ?? false;

  const providerRules = rulesFromCapabilities(providerCapabilities);
  const sourceRules = rulesFromCapabilities(sourceCapabilities);
  const blockedHosts = [...(providerRules.blockedHosts ?? []), ...(sourceRules.blockedHosts ?? [])];
  const blockedPathPrefixes = [...(providerRules.blockedPathPrefixes ?? []), ...(sourceRules.blockedPathPrefixes ?? [])];

  const config: PlaybackAdProtectionConfig = { enabled };
  if (blockedHosts.length) config.blockedHosts = blockedHosts;
  if (blockedPathPrefixes.length) config.blockedPathPrefixes = blockedPathPrefixes;
  return config;
}

/**
 * Form-persist helper (mirrors `withSandboxPolicy`): merges the admin toggle
 * into a capabilities object. Return type is intentionally inferred (spread
 * style) so the result stays assignable to the database `Json` capabilities
 * column exactly like the sandbox-policy helper it mirrors.
 */
export function withPlaybackAdProtection(capabilities: Record<string, unknown>, enabled: boolean) {
  return { ...capabilities, playback_ad_protection: enabled };
}

/** Admin-facing description shown under the Ad Protection control. */
export function playbackAdProtectionDescription(enabled: boolean): string {
  return enabled
    ? 'Playback ad/redirect protection is ON for this provider/source only. Classified ad/redirect playback URLs are rejected and the resolver falls back to the next source. No other provider or Mavero page is affected.'
    : 'OFF by default. Playback ad/redirect protection runs only for providers/sources where an admin explicitly enables it. Mavero pages and Mavero\'s own advertising are never affected by this setting.';
}
