/**
 * Device pairing service.
 *
 * Manages the lifecycle of QR-based device pairing requests:
 *   create → pending → approved → consumed
 *                     → expired
 *                     → cancelled
 *
 * Security:
 *   - The pairing secret is a 32-byte random string (URL-safe base64).
 *   - Only the SHA-256 hash is stored in the database.
 *   - The raw secret is returned ONCE to the TV that creates the
 *     request. It's encoded in the QR code.
 *   - The short_code is a human-readable fallback (8 chars).
 *   - Requests expire after 5 minutes.
 *   - Single-use: once consumed, the exchange_code is cleared and
 *     status set to 'consumed'.
 *   - The exchange_code is a Supabase OTP code generated by
 *     admin.auth.admin.generateLink() — it allows the TV to call
 *     exchangeCodeForSession(code) to establish its OWN independent
 *     Supabase session (not a copy of the phone's session).
 */

import { createHash } from 'node:crypto';
import type { SupabaseAdminClient } from '$lib/server/supabase/admin';
import { env as publicEnv } from '$env/dynamic/public';
import type { Database } from '$lib/server/supabase/database.types';
import { parseDeviceMetadata, type DeviceMetadata } from './device-metadata';

const PAIRING_TTL_MS = 5 * 60 * 1000; // 5 minutes
const SHORT_CODE_LENGTH = 8;
const SHORT_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no ambiguous chars

export type PairingStatus = 'pending' | 'approved' | 'consumed' | 'expired' | 'cancelled';

export type PairingRequest = {
  id: string;
  secret: string; // raw secret — only returned on creation
  shortCode: string;
  status: PairingStatus;
  deviceType: string;
  deviceName: string;
  browser: string | null;
  os: string | null;
  platform: string | null;
  expiresAt: string;
  createdAt: string;
};

export type PairingStatusResponse = {
  status: PairingStatus;
  exchangeCode: string | null; // only present when 'approved'
};

/**
 * Creates a new pairing request.
 * Called by the unauthenticated TV browser.
 */
export async function createPairingRequest(
  admin: SupabaseAdminClient,
  userAgent: string | null
): Promise<{ pairing: PairingRequest | null; error: string | null }> {
  try {
    // Generate cryptographic random secret (32 bytes, URL-safe base64).
    const secretBytes = new Uint8Array(32);
    crypto.getRandomValues(secretBytes);
    const secret = Buffer.from(secretBytes).toString('base64url');

    // Generate short code.
    const shortCode = generateShortCode();

    // Hash the secret for storage.
    const secretHash = hashSecret(secret);

    // Parse device metadata from the TV's User-Agent.
    const metadata = parseDeviceMetadata(userAgent);

    const expiresAt = new Date(Date.now() + PAIRING_TTL_MS).toISOString();

    const { data, error } = await admin
      .from('device_pairing_requests')
      .insert({
        secret_hash: secretHash,
        short_code: shortCode,
        status: 'pending',
        requested_device_type: metadata.deviceType,
        requested_device_name: metadata.deviceName,
        requested_browser: metadata.browser,
        requested_os: metadata.os,
        requested_platform: metadata.platform,
        expires_at: expiresAt,
      })
      .select('*')
      .single();

    if (error || !data) {
      console.error('[Pairing] Create error', { name: error?.name, code: error?.code });
      return { pairing: null, error: 'Unable to create pairing request.' };
    }

    return {
      pairing: {
        id: data.id,
        secret, // raw — only returned once
        shortCode: data.short_code,
        status: 'pending',
        deviceType: data.requested_device_type,
        deviceName: data.requested_device_name,
        browser: data.requested_browser,
        os: data.requested_os,
        platform: data.requested_platform,
        expiresAt: data.expires_at,
        createdAt: data.created_at,
      },
      error: null,
    };
  } catch (err) {
    console.error('[Pairing] Create exception', { name: (err as Error)?.name ?? 'unknown' });
    return { pairing: null, error: 'Unable to create pairing request.' };
  }
}

/**
 * Looks up a pairing request by its raw secret.
 * Used by the phone authorization page and the TV status polling.
 */
export async function getPairingBySecret(
  admin: SupabaseAdminClient,
  secret: string
): Promise<{ request: PairingStatusResponse | null; error: string | null }> {
  try {
    const secretHash = hashSecret(secret);
    const { data, error } = await admin
      .from('device_pairing_requests')
      .select('status, expires_at, exchange_code, consumed_at')
      .eq('secret_hash', secretHash)
      .maybeSingle();

    if (error) {
      return { request: null, error: 'Unable to lookup pairing request.' };
    }
    if (!data) {
      return { request: null, error: 'Pairing request not found.' };
    }

    // Check expiration.
    const isExpired = new Date(data.expires_at).getTime() < Date.now();
    if (isExpired && data.status === 'pending') {
      // Mark as expired (lazy cleanup).
      await admin
        .from('device_pairing_requests')
        .update({ status: 'expired' })
        .eq('secret_hash', secretHash)
        .eq('status', 'pending');
      return { request: { status: 'expired', exchangeCode: null }, error: null };
    }

    // Only return exchange_code when approved and not yet consumed.
    const exchangeCode = (data.status === 'approved' && !data.consumed_at) ? data.exchange_code : null;

    return {
      request: { status: data.status as PairingStatus, exchangeCode },
      error: null,
    };
  } catch {
    return { request: null, error: 'Unable to lookup pairing request.' };
  }
}

/**
 * Looks up a pairing request by its short code.
 * Used by the manual code entry fallback.
 */
export async function getPairingByShortCode(
  admin: SupabaseAdminClient,
  shortCode: string
): Promise<{ request: PairingRequest | null; error: string | null }> {
  try {
    const { data, error } = await admin
      .from('device_pairing_requests')
      .select('*')
      .eq('short_code', shortCode.toUpperCase())
      .eq('status', 'pending')
      .maybeSingle();

    if (error || !data) {
      return { request: null, error: 'Invalid or expired code.' };
    }

    // Check expiration.
    if (new Date(data.expires_at).getTime() < Date.now()) {
      await admin
        .from('device_pairing_requests')
        .update({ status: 'expired' })
        .eq('id', data.id)
        .eq('status', 'pending');
      return { request: null, error: 'This code has expired.' };
    }

    return {
      request: {
        id: data.id,
        secret: '', // NOT returned for short-code lookup (phone needs the secret to approve)
        shortCode: data.short_code,
        status: 'pending',
        deviceType: data.requested_device_type,
        deviceName: data.requested_device_name,
        browser: data.requested_browser,
        os: data.requested_os,
        platform: data.requested_platform,
        expiresAt: data.expires_at,
        createdAt: data.created_at,
      },
      error: null,
    };
  } catch {
    return { request: null, error: 'Unable to lookup pairing request.' };
  }
}

/**
 * Approves a pairing request.
 * Called by the authenticated phone user.
 *
 * Uses Supabase admin.auth.admin.generateLink() to create a magic
 * link for the approving user. The OTP code from the link is stored
 * in the pairing request — the TV will call
 * exchangeCodeForSession(code) to establish its OWN independent
 * Supabase session.
 */
export async function approvePairingRequest(
  admin: SupabaseAdminClient,
  secret: string,
  userId: string,
  userEmail: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const secretHash = hashSecret(secret);

    // 1. Look up the pairing request.
    const { data: pairing, error: lookupError } = await admin
      .from('device_pairing_requests')
      .select('id, status, expires_at')
      .eq('secret_hash', secretHash)
      .maybeSingle();

    if (lookupError || !pairing) {
      return { success: false, error: 'Pairing request not found.' };
    }

    // 2. Check status.
    if (pairing.status !== 'pending') {
      return { success: false, error: `This request is already ${pairing.status}.` };
    }

    // 3. Check expiration.
    if (new Date(pairing.expires_at).getTime() < Date.now()) {
      await admin
        .from('device_pairing_requests')
        .update({ status: 'expired' })
        .eq('id', pairing.id);
      return { success: false, error: 'This request has expired.' };
    }

    // 4. Generate a magic link for the user via Supabase admin API.
    //    This creates an OTP code that the TV browser can use with
    //    exchangeCodeForSession(code) to establish its own session.
    const supabaseUrl = publicEnv.PUBLIC_SUPABASE_URL;
    const { data: linkData, error: linkError } = await admin.auth.admin.generateLink({
      type: 'magiclink',
      email: userEmail,
    });

    if (linkError || !linkData) {
      console.error('[Pairing] generateLink error', { name: linkError?.name, code: linkError?.code });
      return { success: false, error: 'Unable to authorize this device right now.' };
    }

    // Extract the OTP code from the magic link URL.
    // The hashed_token is what exchangeCodeForSession expects.
    const exchangeCode = linkData.properties?.hashed_token;
    if (!exchangeCode) {
      console.error('[Pairing] No hashed_token in generateLink response');
      return { success: false, error: 'Unable to authorize this device right now.' };
    }

    // 5. Atomically update: pending → approved + store exchange_code.
    //    The .eq('status', 'pending') ensures only one approval can
    //    succeed (race condition protection).
    const { error: updateError } = await admin
      .from('device_pairing_requests')
      .update({
        status: 'approved',
        approved_by_user_id: userId,
        approved_at: new Date().toISOString(),
        exchange_code: exchangeCode,
      })
      .eq('id', pairing.id)
      .eq('status', 'pending');

    if (updateError) {
      // Could be a race condition — another approval already happened.
      return { success: false, error: 'This request may have already been processed.' };
    }

    return { success: true, error: null };
  } catch (err) {
    console.error('[Pairing] Approve exception', { name: (err as Error)?.name ?? 'unknown' });
    return { success: false, error: 'Unable to approve the pairing request.' };
  }
}

/**
 * Cancels a pairing request.
 * Called by the phone user (or automatically on TV page unload).
 */
export async function cancelPairingRequest(
  admin: SupabaseAdminClient,
  secret: string
): Promise<boolean> {
  try {
    const secretHash = hashSecret(secret);
    const { error } = await admin
      .from('device_pairing_requests')
      .update({ status: 'cancelled' })
      .eq('secret_hash', secretHash)
      .eq('status', 'pending');

    return !error;
  } catch {
    return false;
  }
}

/**
 * Marks a pairing request as consumed.
 * Called after the TV successfully exchanges the code for a session.
 */
export async function consumePairingRequest(
  admin: SupabaseAdminClient,
  secret: string
): Promise<boolean> {
  try {
    const secretHash = hashSecret(secret);
    const { error } = await admin
      .from('device_pairing_requests')
      .update({
        status: 'consumed',
        consumed_at: new Date().toISOString(),
        exchange_code: null, // Clear the code — single-use
      })
      .eq('secret_hash', secretHash)
      .eq('status', 'approved'); // Only approved requests can be consumed

    return !error;
  } catch {
    return false;
  }
}

// --- Helpers ---

function hashSecret(secret: string): string {
  return createHash('sha256').update(secret).digest('hex');
}

function generateShortCode(): string {
  const chars: string[] = [];
  const bytes = new Uint8Array(SHORT_CODE_LENGTH);
  crypto.getRandomValues(bytes);
  for (let i = 0; i < SHORT_CODE_LENGTH; i++) {
    chars.push(SHORT_CODE_ALPHABET[bytes[i] % SHORT_CODE_ALPHABET.length]);
  }
  return chars.join('');
}
