#!/usr/bin/env node
/**
 * MAVERO — bundles the adapter-build-executor Netlify BACKGROUND function.
 *
 * Output: netlify/functions/adapter-build-executor.mjs
 * Source:  scripts/executor-entry.ts
 *
 * WHY THIS EXISTS: the durable build lifecycle (migration
 * 20261102000000) executes builds in a Netlify background function
 * (invoked with a 202-immediate POST; 15-minute execution budget). The
 * function needs the FULL SvelteKit server build pipeline
 * (build-lifecycle.ts + its transitive closure), which uses `$lib` /
 * `$env/dynamic/private` aliases that Netlify's own function bundler
 * cannot resolve — so we pre-bundle with esbuild here (esbuild is an
 * existing project dependency).
 *
 * The generated file is a BUILD ARTIFACT (git-ignored; regenerated by
 * every `pnpm build` — the Netlify build command runs it before deploy).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const outFile = path.join(repoRoot, 'netlify', 'functions', 'adapter-build-executor.mjs');

// esbuild is a transitive dependency (via vite) in pnpm's strict layout —
// resolve it from vite's own module context so this works in every
// environment that can build the app (local + Netlify).
const requireFromRepo = createRequire(import.meta.url);
const requireFromVite = createRequire(requireFromRepo.resolve('vite'));
const esbuild = requireFromVite('esbuild');

mkdirSync(path.dirname(outFile), { recursive: true });

await esbuild.build({
  entryPoints: [path.join(repoRoot, 'scripts', 'executor-entry.ts')],
  outfile: outFile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: false,
  minify: false,
  legalComments: 'none',
  alias: {
    // SvelteKit aliases (vite resolves these for the app; esbuild for us).
    $lib: path.join(repoRoot, 'src', 'lib'),
    // The dynamic private env module → the process.env shim (Netlify
    // injects site env vars into the function runtime).
    '$env/dynamic/private': path.join(repoRoot, 'scripts', 'executor-shims', 'env-dynamic-private.ts'),
  },
  // Node built-ins stay external; @supabase/supabase-js + everything else
  // bundles INTO the file so the deployed function is self-contained
  // except for the Netlify-provided node runtime.
  packages: 'bundle',
  banner: {
    js: [
      '// MAVERO adapter-build-executor — GENERATED FILE (scripts/build_executor_function.mjs).',
      '// Do not edit; regenerate with `pnpm build`.',
      "import { createRequire as __createRequire } from 'node:module';",
      'const require = __createRequire(import.meta.url);',
    ].join('\n'),
  },
});

// The v2 function config must survive bundling: re-assert it (esbuild
// keeps the `config` export, but assert to be safe).
writeFileSync(
  path.join(repoRoot, 'netlify', 'functions', 'adapter-build-executor.config.json'),
  JSON.stringify({ type: 'background' }, null, 2) + '\n',
);

console.log('[build_executor_function] wrote', path.relative(repoRoot, outFile));
