-- ============================================================
-- Big-Screen QR production regression repair — exchange lease
-- state machine + manual-code authorization handles
-- ============================================================
--
-- CONTEXT (post-94ce1ef real-device audit):
-- The deployed claim_device_pairing RPC flipped an approved
-- pairing to 'consumed' and cleared exchange_code BEFORE the
-- Supabase token verification ran. When verification failed (the
-- exchangeCodeForSession(hashed_token) API misuse — fixed in the
-- application layer), the pairing was permanently dead: consumed,
-- credential cleared, user forced to re-pair. This migration
-- introduces a lease-based state machine so a failed exchange can
-- SAFELY recover, and adds manual-code authorization handles for
-- the phone-side "Enter TV code" path.
--
-- NEW STATE MACHINE:
--
--   pending
--      ↓ (phone approves — stores exchange_code)
--   approved
--      ↓ claim_device_pairing() — atomic, 30s lease
--   exchanging  ←──────────── release_device_pairing_exchange()
--      ↓ verifyOtp (token_hash, type 'email')     ↺ recoverable
--      ↓ transient failure → release → approved (retry allowed)
--      ↓ success
--   consumed  (complete_device_pairing — clears credential)
--
--      ↓ unrecoverable failure (OTP expired/consumed at Supabase)
--   failed    (fail_device_pairing — clears credential)
--
--   Any of pending/exchanging lazily → expired once expires_at
--   passes (bounded lifetime — no permanent stuck state).
--
-- PROPERTIES:
--   - one-time use: only 'approved' (or a lease-EXPIRED
--     'exchanging') rows are claimable; 'consumed'/'failed' are
--     terminal and never claimable again.
--   - race-safe: select ... FOR update serializes concurrent
--     claims on the same row.
--   - replay-safe: after consumption the claim finds no eligible
--     row; the credential is cleared.
--   - no permanent dead state: a crashed exchangeer holds the
--     lease for at most EXCHANGE_LEASE_MS; afterwards a new claim
--     takes over. The pairing's own expires_at bounds everything.
--   - bounded retries: exchange_attempts is incremented per
--     claim; beyond MAX_EXCHANGE_ATTEMPTS the pairing is marked
--     'failed' (protects the Supabase verify endpoint from
--     unbounded retry hammering).
--
-- MANUAL-CODE HANDLES (phone "Enter TV code" path):
--   The 8-char short code has ~2^40 entropy — far lower than the
--   256-bit pairing secret. The phone NEVER receives the pairing
--   secret for a code lookup. Instead, an AUTHENTICATED, rate-
--   limited lookup returns a one-time 32-byte URL-safe handle
--   (hashed at rest, bound to the resolving user, 2-minute TTL)
--   that authorizes the SAME approval pipeline as the QR secret.
--
-- This is a NEW FORWARD migration. The already-applied
-- 20260929000000_device_pairing_claim_rpc.sql is not modified
-- (production migration history is immutable — its function is
-- replaced here via drop + create).
-- ============================================================

-- ------------------------------------------------------------
-- 1. Table: extended status set + lease columns + manual handle
-- ------------------------------------------------------------

-- Drop the old status check and add the extended one. The old
-- constraint name is auto-generated by PostgreSQL
-- (device_pairing_requests_status_check) — drop by name with an
-- unknown-name fallback that looks it up dynamically, so this
-- migration works even if the deployed constraint name differs.
do $$
declare
  v_constraint text;
begin
  select conname into v_constraint
  from pg_constraint
  where conrelid = 'public.device_pairing_requests'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ILIKE '%status%'
    and conname LIKE '%status%check%';
  if v_constraint is not NULL then
    execute format('alter table public.device_pairing_requests drop constraint %I', v_constraint);
  end if;
end
$$;

alter table public.device_pairing_requests
  add constraint device_pairing_requests_status_check
  check (status IN ('pending', 'approved', 'exchanging', 'consumed', 'failed', 'expired', 'cancelled'));

alter table public.device_pairing_requests
  add column if not EXISTS exchange_lease_until timestamptz,
  add column if not EXISTS exchange_claimed_at timestamptz,
  add column if not EXISTS exchange_attempts int not NULL default 0;

-- Manual-code authorization handle (phone "Enter TV code" path).
-- manual_handle_hash: SHA-256 of the raw handle (never stored raw).
-- manual_handle_user_id: the authenticated user who resolved the
--   short code — the handle is bound to that session and unusable
--   by any other account.
-- manual_handle_expires_at: 2-minute TTL.
alter table public.device_pairing_requests
  add column if not EXISTS manual_handle_hash text,
  add column if not EXISTS manual_handle_user_id uuid,
  add column if not EXISTS manual_handle_expires_at timestamptz;

-- ------------------------------------------------------------
-- 2. Indexes
-- ------------------------------------------------------------
-- The original partial index only covered status='pending'; the
-- claim (approved / lease-expired exchanging) and the diagnostic
-- lookups (any status) needed a seq scan. A full index on
-- secret_hash serves every state transition + status polling.
create index if not EXISTS device_pairing_secret_hash_all_idx
  on public.device_pairing_requests (secret_hash);

-- Manual handle lookups (phone authorize page, handle path).
create index if not EXISTS device_pairing_manual_handle_idx
  on public.device_pairing_requests (manual_handle_hash)
  where manual_handle_hash is not NULL;

-- ------------------------------------------------------------
-- 3. Replace claim_device_pairing with the lease-aware version
-- ------------------------------------------------------------
-- The 20260929000000 RPC had signature (text, timestamptz) and
-- flipped approved → consumed in one step. The new contract has a
-- DIFFERENT signature, so the old function is DROPPED first —
-- create or replace with different args would silently create an
-- overload and PostgREST would then face call ambiguity.

drop function if EXISTS public.claim_device_pairing(text, timestamptz);

create or replace function public.claim_device_pairing(
  p_secret_hash text,
  p_lease_ms int default 30000,
  p_max_attempts int default 5,
  p_now timestamptz default timezone('utc', now())
)
returns table(
  id uuid,
  exchange_code text,
  exchange_attempts int
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row record;
begin
  -- Step 1: select ... FOR update — serializes concurrent claims.
  -- Eligible rows:
  --   a) status = 'approved'  (normal first claim), or
  --   b) status = 'exchanging' and the lease has EXPIRED
  --      (the previous exchangeer crashed / went away — a fresh
  --      claim takes over the SAME stored credential).
  -- Ineligible: pending (not approved yet), consumed / failed
  -- (terminal — replay protection), cancelled / expired.
  select id, exchange_code, exchange_attempts into v_row
  from public.device_pairing_requests
  where secret_hash = p_secret_hash
    and expires_at > p_now
    and consumed_at is null
    and (
      status = 'approved'
      or (
        status = 'exchanging'
        and exchange_lease_until is not NULL
        and exchange_lease_until < p_now
      )
    )
  order BY created_at desc
  for update;

  if not found then
    -- No eligible row — empty result set. The application layer
    -- performs a status-only diagnostic lookup to pick the right
    -- HTTP code (404 / 409 / 410).
    return;
  end if;

  -- Step 2: attempt-cap enforcement. Too many claims on one
  -- pairing means something is systematically wrong — mark the
  -- pairing failed (terminal) instead of letting a client hammer
  -- the Supabase verify endpoint forever.
  if v_row.exchange_attempts >= p_max_attempts then
    update public.device_pairing_requests
    set status = 'failed',
        exchange_lease_until = NULL,
        exchange_code = null
    where id = v_row.id;
    return;
  end if;

  -- Step 3: flip to 'exchanging' with a fresh lease. The
  -- exchange_code is KEPT in the row (unlike the old design) so
  -- that a recoverable failure can retry with the same credential
  -- after release_device_pairing_exchange() or a lease takeover.
  -- The credential remains RLS-locked away from every client
  -- role; its at-rest lifetime is bounded by the pairing expiry.
  update public.device_pairing_requests
  set status = 'exchanging',
      exchange_lease_until = p_now + make_interval(ms => p_lease_ms),
      exchange_claimed_at = p_now,
      exchange_attempts = v_row.exchange_attempts + 1
  where id = v_row.id;

  -- Step 4: return the credential + attempt count. It lives only
  -- in the RPC result set → application memory → verifyOtp call.
  return query select v_row.id::uuid, v_row.exchange_code::text,
                      (v_row.exchange_attempts + 1)::int;
end;
$$;

-- ------------------------------------------------------------
-- 4. complete_device_pairing — exchanging → consumed (success)
-- ------------------------------------------------------------
-- Called by the exchange endpoint AFTER verifyOtp succeeded and
-- the session cookies were written to the TV response. Clears the
-- credential and the lease in the same atomic statement.
-- p_pairing_id binds the completion to the exact claim cycle the
-- caller won (defense in depth against stale completion calls).

create or replace function public.complete_device_pairing(
  p_secret_hash text,
  p_pairing_id uuid,
  p_now timestamptz default timezone('utc', now())
)
returns table(id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  update public.device_pairing_requests
  set status = 'consumed',
      consumed_at = p_now,
      exchange_code = null,
      exchange_lease_until = NULL
  where secret_hash = p_secret_hash
    and id = p_pairing_id
    and status = 'exchanging'
  RETURNING id into v_id;

  if v_id is not NULL then
    return query select v_id;
  end if;
end;
$$;

-- ------------------------------------------------------------
-- 5. release_device_pairing_exchange — exchanging → approved
-- ------------------------------------------------------------
-- Called when the Supabase verification failed in a way that did
-- not consume the credential (transient network error, 5xx, a
-- lease-busy retry path). The stored credential is KEPT so the
-- TV can retry the exchange with the SAME one-time token. This is
-- the "safely recover to approved" transition.
--
-- It is not called when GoTrue reports the token as expired or
-- already consumed — in that case the credential is dead and the
-- pairing goes to fail_device_pairing instead. Replaying a
-- consumed auth credential is therefore impossible.

create or replace function public.release_device_pairing_exchange(
  p_secret_hash text,
  p_pairing_id uuid
)
returns table(id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  update public.device_pairing_requests
  set status = 'approved',
      exchange_lease_until = NULL
  where secret_hash = p_secret_hash
    and id = p_pairing_id
    and status = 'exchanging'
  RETURNING id into v_id;

  if v_id is not NULL then
    return query select v_id;
  end if;
end;
$$;

-- ------------------------------------------------------------
-- 6. fail_device_pairing — exchanging → failed (terminal)
-- ------------------------------------------------------------
-- Called when the credential is definitively dead (GoTrue
-- otp_expired / invalid) or the cookie establishment failed after
-- a successful verification (the token was consumed, so a retry
-- can never succeed). Terminal: the row can never be claimed
-- again. Clears the credential.

create or replace function public.fail_device_pairing(
  p_secret_hash text,
  p_pairing_id uuid,
  p_now timestamptz default timezone('utc', now())
)
returns table(id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  update public.device_pairing_requests
  set status = 'failed',
      consumed_at = p_now,
      exchange_code = null,
      exchange_lease_until = NULL
  where secret_hash = p_secret_hash
    and id = p_pairing_id
    and status = 'exchanging'
  RETURNING id into v_id;

  if v_id is not NULL then
    return query select v_id;
  end if;
end;
$$;

-- ------------------------------------------------------------
-- 7. Privilege lockdown + service_role grants
-- ------------------------------------------------------------
-- Same convention as 20260929000000: execute revoked from
-- PUBLIC/anon/authenticated; explicitly granted to service_role
-- (the only role the application's admin client uses). Supabase's
-- service_role bypasses RLS but not missing execute privileges.

revoke execute on function public.claim_device_pairing(text, int, int, timestamptz) from PUBLIC;
revoke execute on function public.claim_device_pairing(text, int, int, timestamptz) from authenticated;
revoke execute on function public.claim_device_pairing(text, int, int, timestamptz) from anon;
grant execute on function public.claim_device_pairing(text, int, int, timestamptz) to service_role;

revoke execute on function public.complete_device_pairing(text, uuid, timestamptz) from PUBLIC;
revoke execute on function public.complete_device_pairing(text, uuid, timestamptz) from authenticated;
revoke execute on function public.complete_device_pairing(text, uuid, timestamptz) from anon;
grant execute on function public.complete_device_pairing(text, uuid, timestamptz) to service_role;

revoke execute on function public.release_device_pairing_exchange(text, uuid) from PUBLIC;
revoke execute on function public.release_device_pairing_exchange(text, uuid) from authenticated;
revoke execute on function public.release_device_pairing_exchange(text, uuid) from anon;
grant execute on function public.release_device_pairing_exchange(text, uuid) to service_role;

revoke execute on function public.fail_device_pairing(text, uuid, timestamptz) from PUBLIC;
revoke execute on function public.fail_device_pairing(text, uuid, timestamptz) from authenticated;
revoke execute on function public.fail_device_pairing(text, uuid, timestamptz) from anon;
grant execute on function public.fail_device_pairing(text, uuid, timestamptz) to service_role;
